### ISSUE TITLE
DryWetMIDI : Need to change MogLib NuGet package

### ISSUE THREAD

**Issue by melanchall** [BardMusicPlayer/MogLib#2]
Hi,

I'm the author of DryWetMIDI. In NuGet I see your package as:

![image](https://user-images.githubusercontent.com/26361185/115707203-2ad57500-a377-11eb-8b9f-246cd03c7a77.png)

You use the same info for your package as I use for the my one (logo, text). Even my username. But I didn't publish this package.

Please delete the package from the NuGet and publish your own, with your username, your info and so on. I hope you'll do this as soon as possible.

**Comment by MoogleTroupe** [comment]
I delisted it. Are you able to post preview builds of drywet tagged as preview, with the thread and strong name changes I pr'd?

**Comment by melanchall** [comment]
Thanks. Yes, preview version is good suggestion. I'll try to setup my CI process to easily deploy preview versions of the library.

**Comment by MoogleTroupe** [comment]
thank you!!

**Comment by melanchall** [comment]
@MoogleTroupe I've published pre-release package: https://www.nuget.org/packages/Melanchall.DryWetMidi/5.2.1-prerelease5

**Comment by MoogleTroupe** [comment]
Thank you!
